version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Checking java version...
      - java -version
  build:
    commands:
      - echo Building project...
      - echo Build started on `date`
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml