version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
      docker: 19
    commands:
      - echo Checking java version...
      - java -version
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 421904971359.dkr.ecr.us-east-1.amazonaws.com
      - docker pull $CONTAINER_REPOSITORY_URL:$TAG_NAME || true
  build:
    commands:
      - echo Building project...
      - echo Build started on `date`
      - mvn package
      - docker build -t student-enrollment .
      - docker tag student-enrollment:latest $CONTAINER_REPOSITORY_URL:$TAG_NAME
  post_build:
    commands:
      - docker push $CONTAINER_REPOSITORY_URL:$TAG_NAME
      - echo Build completed on `date`

artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yml